//------ ------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeritageProjectGrp6.Models
{
    using System;
    
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.IdentityModel;
    public partial class AYANTDROIT
    {
        [Key]
        public int ADRID { get; set; }
        public Nullable<int> NOMENCLATUREID { get; set; }
        public int UTILISATEURID { get; set; }
        public string DESIGNATION { get; set; }
        public byte[] IMAGEADR { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public string TYPEHERITIER { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public Nullable<System.DateTime> DATENAISSANCE { get; set; }
        public string SEXE { get; set; }

        public virtual UTILISATEUR UTILISATEUR { get; set; }
        public virtual HERITIER HERITIER { get; set; }

    }
}
