//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeritageProjectGrp6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class HERITAGE
    {



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public HERITAGE()
        {
            this.BIENS = new HashSet<BIENS>();
            this.ECOLE = new HashSet<ECOLE>();
        }


        public int HERITAGEID { get; set; }
        public int NOMENCLATUREID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE_DECES { get; set; }
        public Nullable<System.DateTime> DATE_HERITAGE { get; set; }
        public Nullable<int> ECOLEID { get; set; }
        public Nullable<decimal> MONTANT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENS> BIENS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECOLE> ECOLE { get; set; }
        public virtual HERITIER HERITIER { get; set; }
    }
}
