//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeritagesProjectG6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECOLE
    {
        public int ECOLEID { get; set; }
        public int HERITAGEID { get; set; }
        public int REGLEID { get; set; }
        public string NOM { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual REGLE REGLE { get; set; }
        public virtual HERITAGE HERITAGE { get; set; }
    }
}
