//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeritagesProjectG6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HERITIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HERITIER()
        {
            this.AYANTDROIT = new HashSet<AYANTDROIT>();
            this.HERITAGE = new HashSet<HERITAGE>();
        }
    
        public int NOMENCLATUREID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> CODE { get; set; }
        public Nullable<bool> ILLLUSTRATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AYANTDROIT> AYANTDROIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HERITAGE> HERITAGE { get; set; }
    }
}
